[package]
name = "wild-proxy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
libwild-proxy = { path = "../libwild-proxy" }
anyhow = "1.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
